server:
  port: 8090
#配置数据库
spring:
  datasource:
    username: root
    password: loveQueena1991
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.110:3308/one_office?characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      auto-commit: true
      connection-test-query: select 1
      connection-timeout: 30000
      max-lifetime: 1800000
jwt:
  #jwt 存储的请求头
  tokenHeader: Authorization
  #jwt 加密使用的秘钥
  secret: one-office-oss
  #jwt 超期时间：60*60*24
  expiration: 86400
  #jwt 负荷中拿到的开头
  tokenHead: Bearer

#设置springSecurity放行资源地址
security:
  release-url: /user/login.do,/user/logOut.do,/css/**,/js/**,/index.html,favicon.ico,/doc.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**

#配置swagger信息
swagger:
    base-package: com.jiashn.oneofficesso.user  #api路径
    title: 一个办公-后端接口服务   #接口标题
    description: 一个办公-后端接口服务      #接口描述
    version: 1.0                #接口版本

mybatis-plus:
  mapper-locations: classpath*:/mapper/com/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl